final changes

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -76,12 +76,4 @@ jobs:
 
     - name: Verify API Endpoint
       run: |
-        API_URL=$(http://34.70.29.153)
-        RESPONSE=$(curl -s $API_URL/time)
-        if echo "$RESPONSE" | grep -q '"current_time"'; then
-          echo "API is accessible and returned the correct response."
-        else
-          echo "API test failed."
-          exit 1
-        fi
-      working-directory: terraform/
+        curl -sf http://34.70.29.153/time | grep '"current_time"' || { echo "API test failed"; exit 1; }
